// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_WEB', defaultValue: ''),
    appId: '1:679661724443:web:b10c36dc4bc0a290dfe9be',
    messagingSenderId: '679661724443',
    projectId: 'delhinightsapps',
    authDomain: 'delhinightsapps.firebaseapp.com',
    storageBucket: 'delhinightsapps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_ANDROID', defaultValue: ''),
    appId: '1:679661724443:android:d71267a88370293fdfe9be',
    messagingSenderId: '679661724443',
    projectId: 'delhinightsapps',
    storageBucket: 'delhinightsapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_IOS', defaultValue: ''),
    appId: '1:679661724443:ios:b10c36dc4bc0a290dfe9be',
    messagingSenderId: '679661724443',
    projectId: 'delhinightsapps',
    storageBucket: 'delhinightsapps.appspot.com',
    iosClientId: '679661724443-n2e6qvs0ks0cr0u1j7q0nhu3j5h5qvs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_MACOS', defaultValue: ''),
    appId: '1:679661724443:ios:b10c36dc4bc0a290dfe9be',
    messagingSenderId: '679661724443',
    projectId: 'delhinightsapps',
    storageBucket: 'delhinightsapps.appspot.com',
    iosClientId: '679661724443-n2e6qvs0ks0cr0u1j7q0nhu3j5h5qvs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantApp',
  );

  // For Windows desktop, FlutterFire uses Web-style credentials.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_WINDOWS', defaultValue: ''),
    appId: '1:679661724443:web:b10c36dc4bc0a290dfe9be',
    messagingSenderId: '679661724443',
    projectId: 'delhinightsapps',
    storageBucket: 'delhinightsapps.appspot.com',
  );
}
